Repository TheMuppet/DAYO, pull requests merged in 2022-03, with the labels that each got.

#17 Landing page
  .github/workflows/build-web.yml
  deps/web/Procfile
  deps/web/deps.ts
  web/backend/controller/test_controller.ts
  web/backend/routes/routes.ts
  web/backend/server.ts
  web/frontend/.gitignore
  web/frontend/dist/images/dayo_transparent_small.png
  web/frontend/dist/images/logo_transparent.png
  web/frontend/public/bootstrap.min.css
  web/frontend/public/favicons/android-chrome-192x192.png
  web/frontend/public/favicons/apple-touch-icon.png
  web/frontend/public/favicons/browserconfig.xml
  web/frontend/public/favicons/favicon-16x16.png
  web/frontend/public/favicons/favicon-32x32.png
  web/frontend/public/favicons/favicon.ico
  web/frontend/public/favicons/mstile-150x150.png
  web/frontend/public/favicons/site.webmanifest
  web/frontend/public/global.css
  web/frontend/public/images/dayo_transparent_small.png
  web/frontend/public/images/logo_transparent.png
  web/frontend/public/index.html
  web/frontend/src/App.svelte
  web/frontend/src/components/Home.svelte
  web/frontend/src/components/Impressum.svelte
  web/frontend/src/main.js
Labels: enhancement

#21 Show matches in frontend
  .github/workflows/build-web.yml
  .github/workflows/deno.yml
  deno.json
  deps/web/deps.ts
  web/backend/routes/routes.ts
  web/backend/server.ts
  web/frontend/src/App.svelte
  web/frontend/src/components/Match.svelte
  web/frontend/src/components/Matches.svelte
  web/frontend/src/components/UI/Card.svelte
Labels: enhancement

#26 fixed command bot
  README.md
  discord/commands/commands.ts
  discord/commands/placeBet.ts
  discord/commands/showBet.ts
  discord/main.ts
Labels: bug

#24 Git actions to automate trex run build
  .github/workflows/build-web.yml
  web/frontend/dist/0199bdff2c6c41d87f1b3de67b4dc657d9a929fc01b575f493ccfc3a0957ea84.png
  web/frontend/dist/15bd67c4831477e8fec52504b64ab0b062afc9e1eafa3d3c226bd63d10e5f701.webmanifest
  web/frontend/dist/1e1a4dfef61d0c41898cfc47a50d805543b0d904a20ea3d943a74cbdfa886766.png
  web/frontend/dist/2754f169560d102a39ba9dec558125d6199a90acafc1a1f199817bb6a58788fa.png
  web/frontend/dist/35ac889b78f0820ea9dc414eb017edc21149996df003158cc44bccc379d31b3b.png
  web/frontend/dist/49af597b144df11f3cd5e154eaa7a078a8c116d0380de0c76179887d949a131d.png
  web/frontend/dist/4a207c27150bc2f0533d254150fa9b520d159e153ff9a9c319822679cbbb182e.png
  web/frontend/dist/4e8daa79f754cc734d59f0cfcc7adac849dd6e6ab0bd951e14fedb74a4f029ff.png
  web/frontend/dist/83b0a281833f5bd0c7fdc6f54ee9c7f9317a0f25843319c3d5012becd41a2c47.css
  web/frontend/dist/83fc708bf42f305b8eb8f5308635731c6ec70fc287da9e39715beead091685b1.png
  web/frontend/dist/91cb660ca0a4c200f0f67d7cc4e2d987fb3a1922920eca86a6c16c99f86b6ae5.js
  web/frontend/dist/a3e1a9275cb897af5df6c5a49338ccb0c49819b4a1b66d045fad35e956f8f855.webmanifest
  web/frontend/dist/bc8a8be16f74d68f84183c5dd4fb311be7b0eb1500bd3a9270532f5aa1007319.js
  web/frontend/dist/index.html
Labels: enhancement

#31 Show possibilities and matches using discord commands
  README.md
  deps/discord/deps.ts
  discord/commands/matches.ts
  discord/commands/placeBet.ts
  discord/commands/showBet.ts
  discord/main.ts
  web/backend/controller/matchBoxController.ts
  web/backend/controller/matchController.ts
  web/backend/controller/matchNightController.ts
  web/backend/controller/participantController.ts
  web/backend/db/schemas.ts
  web/backend/db/schemas/bets.ts
  web/backend/db/schemas/matchBox.ts
  web/backend/db/schemas/matchNight.ts
  web/backend/db/schemas/matches.ts
  web/backend/db/schemas/participant.ts
  web/backend/schemas/matches.ts
  web/backend/schemas/participant.ts
Labels: enhancement

#33 Update frontend for matches + fetching api
  web/backend/controller/participantController.ts
  web/backend/db/schemas/participant.ts
  web/backend/routes/routes.ts
  web/frontend/src/App.svelte
  web/frontend/src/components/Match.svelte
  web/frontend/src/components/Matches.svelte
  web/frontend/src/components/UI/Card.svelte
Labels: enhancement

#35 27 hot or not
  README.md
  deps/discord/deps.ts
  discord/commands/hotOrNot.ts
  discord/commands/util.ts
  discord/main.ts
  img/DAYO.png
  img/hotOrNotMarie.png
  img/hotOrNotMarius.png
  img/inviteButton.png
  template.env
Labels: enhancement

#38 37 refactor deleting web folder
  .github/workflows/build-web.yml
  .gitignore
  backend/controller/matchBoxController.ts
  backend/controller/matchController.ts
  backend/controller/matchNightController.ts
  backend/controller/participantController.ts
  backend/db/mongo.ts
  backend/db/schemas/admin.ts
  backend/db/schemas/bets.ts
  backend/db/schemas/matchBox.ts
  backend/db/schemas/matchNight.ts
  backend/db/schemas/matches.ts
  backend/db/schemas/participant.ts
  backend/routes/routes.ts
  backend/server.ts
  deps/web/Procfile
  discord/commands/addMatchBox.ts
  discord/commands/addMatchNight.ts
  discord/commands/hotOrNot.ts
  discord/commands/placeBet.ts
  discord/commands/showBet.ts
  discord/commands/showMatches.ts
  discord/commands/util.ts
  discord/main.ts
  discord/tests/util.test.ts
  frontend/public/bootstrap.min.css
  frontend/public/favicons/android-chrome-192x192.png
  frontend/public/favicons/apple-touch-icon.png
  frontend/public/favicons/browserconfig.xml
  frontend/public/favicons/favicon-16x16.png
  frontend/public/favicons/favicon-32x32.png
  frontend/public/favicons/favicon.ico
  frontend/public/favicons/mstile-150x150.png
  frontend/public/favicons/site.webmanifest
  frontend/public/global.css
  frontend/public/images/dayo_transparent_small.png
  frontend/public/images/logo_transparent.png
  frontend/public/index.html
  frontend/run.json
  frontend/snel.config.js
  frontend/src/App.svelte
  frontend/src/components/Home.svelte
  frontend/src/components/Impressum.svelte
  frontend/src/components/Match.svelte
  frontend/src/components/Matches.svelte
  frontend/src/main.js
  web/frontend/.gitignore
  web/frontend/dist/15bd67c4831477e8fec52504b64ab0b062afc9e1eafa3d3c226bd63d10e5f701.webmanifest
  web/frontend/dist/83b0a281833f5bd0c7fdc6f54ee9c7f9317a0f25843319c3d5012becd41a2c47.css
  web/frontend/dist/bc8a8be16f74d68f84183c5dd4fb311be7b0eb1500bd3a9270532f5aa1007319.js
  web/frontend/dist/index.html
  web/frontend/public/favicons/android-chrome-192x192.png
  web/frontend/public/favicons/favicon-16x16.png
  web/frontend/public/favicons/favicon-32x32.png
  web/frontend/public/images/dayo_transparent_small.png
  web/frontend/public/images/logo_transparent.png
Labels: Refactor

#41 Refactor frontend
  frontend/src/App.svelte
  frontend/src/components/Footer.svelte
  frontend/src/components/Impressum.svelte
  frontend/src/components/Match.svelte
  frontend/src/components/Matches.svelte
  frontend/src/components/Navbar.svelte
  frontend/src/pages/Home.svelte
  frontend/src/pages/Impressum.svelte
  frontend/src/pages/Matches.svelte
Labels: Refactor

#43 Fix routing
  backend/routes/routes.ts
Labels: bug

#44 Fix data transfer between components
  frontend/src/App.svelte
  frontend/src/pages/Matches.svelte
  frontend/src/stores.js
Labels: bug

#47 Add dynamic episode filtering
  frontend/src/pages/Matches.svelte
Labels: enhancement
